version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      #- sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1r58ccb14516j --output-template-file packaged-template.yml
      - sam build
      - sam deploy
  post_build:
    on-failure: ABORT
    commands:
      - chmod +x deploy/script.sh
      - bash deploy/script.sh
artifacts:
  files:
    - packaged-template.yml