version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      #- sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1r58ccb14516j --output-template-file packaged-template.yml
      #- sam build
      #- sam deploy
      - sam package --template-file template.yaml --s3-bucket codedeploy-vls-lambda --output-template-file package.yaml
  post_build:
    on-failure: ABORT
    commands:
      - sam deploy --template-file package.yaml --stack-name sam-app --capabilities CAPABILITY_IAM --no-confirm-changeset
      #- chmod +x deploy/script.sh 
      #- bash deploy/script.sh
artifacts:
  files:
    - package.yaml
